version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: kuharski_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: kuharji
      MYSQL_USER: programski_dostop
      MYSQL_PASSWORD: geslo123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./baza.sql:/docker-entrypoint-initdb.d/baza.sql

  web:
    build: .
    container_name: kuharski_web
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    restart: always

volumes:
  db_data:

